import { useParams } from "react-router-dom";
import { formatDate, statusLabel, type Contestant, type Match, type SpectatorState } from "./tournament.js";
import { useTournament } from "./useTournament.js";

function contestant(match: Match, slot: 1 | 2, people: Map<string, Contestant>) { const id = slot === 1 ? match.player1Id : match.player2Id; return id ? people.get(id) : undefined; }
function Entrant({ player, winner, pending }: { player?: Contestant; winner: boolean; pending: boolean }) { return <div className={"entrant " + (winner ? "winner " : "") + (pending ? "pending" : "")}><span className="seed">{player ? "#" + player.seed : "BYE"}</span><span className="entrant-name">{player?.displayName ?? "BYE"}</span>{winner && <span className="winner-mark" aria-label="Match winner">WIN</span>}</div>; }
function MatchCard({ match, people }: { match: Match; people: Map<string, Contestant> }) { const first = contestant(match, 1, people); const second = contestant(match, 2, people); const pending = match.status === "READY" || match.status === "IN_PROGRESS"; const label = match.status === "BYE" ? "Auto-advance" : pending ? "Up next" : match.status.replaceAll("_", " "); return <article className={"match match-" + match.status.toLowerCase()} aria-label={"Match " + match.position + ": " + label}><Entrant player={first} winner={match.winnerId === first?.id} pending={pending} /><Entrant player={second} winner={match.winnerId === second?.id} pending={pending} /><span className="match-status">{label}</span></article>; }
function Bracket({ state }: { state: SpectatorState }) { const people = new Map(state.contestants.map((item) => [item.id, item])); return <section className="bracket-shell" aria-label="Tournament bracket" tabIndex={0}><div className="bracket">{state.rounds.map((round) => <section className="round" key={round.id} aria-labelledby={"round-" + round.id}><h2 id={"round-" + round.id}>{round.name}</h2><div className="round-matches">{state.matches.filter((match) => match.roundId === round.id).sort((a, b) => a.position - b.position).map((match) => <MatchCard key={match.id} match={match} people={people} />)}</div></section>)}</div></section>; }
function StatusState({ status }: { status: SpectatorState["tournament"]["status"] }) { const copy = { SETUP: "Seeds are being set. The bracket will appear when the tournament begins.", ACTIVE: "Matches update live as results are recorded.", COMPLETED: "This tournament has concluded.", CANCELLED: "This tournament has been cancelled." }[status]; return <p className="status-copy">{copy}</p>; }
export function TournamentPage() { const { publicCode } = useParams(); const { state, loading, notFound, connection, refetch } = useTournament(publicCode); if (loading && !state) return <main className="state-page" aria-busy="true"><div className="slime-loader" /><p>Loading bracket...</p></main>; if (notFound) return <main className="state-page"><h1>Bracket not found</h1><p>Check the public code and try again.</p></main>; if (!state) return <main className="state-page"><h1>Unable to connect</h1><p>The bracket is temporarily unavailable.</p><button onClick={() => void refetch()}>Try again</button></main>; const { tournament } = state; return <main className="tournament-page"><div className="drip drip-one" /><div className="drip drip-two" /><header className="tournament-header"><div><p className="eyebrow">{tournament.venueName}</p><h1>{tournament.tournamentName}</h1><p className="game-name">{tournament.gameName}</p></div><div className="event-meta"><time dateTime={tournament.eventDate}>{formatDate(tournament.eventDate)}</time><span className={"status status-" + tournament.status.toLowerCase()}>{statusLabel(tournament.status)}</span><span className={"connection connection-" + connection} aria-live="polite">{connection === "live" ? "LIVE CONNECTION" : connection.toUpperCase()}</span></div></header><StatusState status={tournament.status} />{tournament.status === "COMPLETED" && state.champion && <section className="champion"><span>CHAMPION</span><strong>{state.champion.displayName}</strong><small>Seed #{state.champion.seed}</small></section>}{tournament.status !== "SETUP" && <Bracket state={state} />}{tournament.status === "SETUP" && <section className="seed-list"><h2>Current seeds</h2>{state.contestants.map((player) => <p key={player.id}><span>#{player.seed}</span>{player.displayName}</p>)}</section>}</main>; }
