import { randomInt, randomUUID } from "node:crypto";
import { createSingleEliminationPlan } from "./single-elimination.js";
import { TournamentService } from "../db/repositories.js";
import type { AuditEventType, Contestant, Match, Round, Tournament } from "../db/types.js";

const clock = () => new Date().toISOString();
export class BracketError extends Error { public constructor(message: string, public readonly code: "INVALID" | "STALE" | "UNSAFE") { super(message); } }
export interface BracketState { tournament: Tournament; contestants: Contestant[]; rounds: Round[]; matches: Match[]; }

export class BracketService {
  public constructor(private readonly persistence: TournamentService) {}
  state(tournamentId: string): BracketState {
    const tournament = this.persistence.tournaments.findById(tournamentId); if (!tournament) throw new BracketError("Tournament not found.", "INVALID");
    return { tournament, contestants: this.persistence.bracket.listContestants(tournamentId), rounds: this.persistence.bracket.listRounds(tournamentId), matches: this.persistence.bracket.listMatches(tournamentId) };
  }
  add(tournamentId: string, organizerId: string, expectedRevision: number, displayName: string): BracketState { return this.setupMutation(tournamentId, organizerId, expectedRevision, "CONTESTANTS_MODIFIED", () => this.persistence.bracket.createContestant({ id: randomUUID(), tournamentId, displayName: validName(displayName), seed: this.persistence.bracket.listContestants(tournamentId).length + 1, status: "ACTIVE" })); }
  bulkAdd(tournamentId: string, organizerId: string, expectedRevision: number, text: string): BracketState {
    const names = text.split(/\r?\n/).map((name) => name.trim()).filter(Boolean).map(validName); if (!names.length) throw new BracketError("No contestant names supplied.", "INVALID");
    return this.setupMutation(tournamentId, organizerId, expectedRevision, "CONTESTANTS_MODIFIED", () => { let seed = this.persistence.bracket.listContestants(tournamentId).length; names.forEach((displayName) => this.persistence.bracket.createContestant({ id: randomUUID(), tournamentId, displayName, seed: ++seed, status: "ACTIVE" })); });
  }
  edit(tournamentId: string, organizerId: string, expectedRevision: number, contestantId: string, displayName: string): BracketState { return this.setupMutation(tournamentId, organizerId, expectedRevision, "CONTESTANTS_MODIFIED", () => { const contestant = this.persistence.bracket.findContestant(contestantId); if (!contestant || contestant.tournamentId !== tournamentId) throw new BracketError("Contestant not found.", "INVALID"); this.persistence.bracket.updateContestantName(contestantId, validName(displayName)); }); }
  remove(tournamentId: string, organizerId: string, expectedRevision: number, contestantId: string): BracketState { return this.setupMutation(tournamentId, organizerId, expectedRevision, "CONTESTANTS_MODIFIED", () => { const contestant = this.persistence.bracket.findContestant(contestantId); if (!contestant || contestant.tournamentId !== tournamentId) throw new BracketError("Contestant not found.", "INVALID"); this.persistence.bracket.deleteContestant(contestantId); this.persistence.bracket.reseed(tournamentId, this.persistence.bracket.listContestants(tournamentId).map((c) => c.id)); }); }
  reorder(tournamentId: string, organizerId: string, expectedRevision: number, ids: string[]): BracketState { return this.setupMutation(tournamentId, organizerId, expectedRevision, "SEEDS_REORDERED", () => this.assertSeedOrder(tournamentId, ids)); }
  randomize(tournamentId: string, organizerId: string, expectedRevision: number): BracketState { return this.setupMutation(tournamentId, organizerId, expectedRevision, "SEEDS_RANDOMIZED", () => { const ids = this.persistence.bracket.listContestants(tournamentId).map((c) => c.id); for (let i = ids.length - 1; i > 0; i--) { const j = randomInt(i + 1); [ids[i], ids[j]] = [ids[j]!, ids[i]!]; } this.persistence.bracket.reseed(tournamentId, ids); }); }
  start(tournamentId: string, organizerId: string, expectedRevision: number): BracketState {
    return this.persistence.transaction(() => { const state = this.assertOwned(tournamentId, organizerId, expectedRevision, "SETUP"); const plan = createSingleEliminationPlan(state.contestants); const timestamp = clock(); const roundIds = new Map<number, string>(); plan.rounds.forEach((round) => { const id = randomUUID(); roundIds.set(round.number, id); this.persistence.bracket.createRound({ id, tournamentId, roundNumber: round.number, name: round.name }); }); const matchIds = new Map<string, string>(); plan.matches.forEach((match) => matchIds.set(`${match.round}:${match.position}`, randomUUID())); plan.matches.slice().reverse().forEach((match) => this.persistence.bracket.createMatch({ id: matchIds.get(`${match.round}:${match.position}`)!, tournamentId, roundId: roundIds.get(match.round)!, position: match.position, player1Id: match.player1Id, player2Id: match.player2Id, winnerId: null, loserId: null, status: "PENDING", nextWinnerMatchId: match.nextRound ? matchIds.get(`${match.nextRound}:${match.nextPosition}`)! : null, nextWinnerSlot: match.nextSlot, createdAt: timestamp, updatedAt: timestamp, completedAt: null })); this.persistence.tournaments.update(tournamentId, expectedRevision, { status: "ACTIVE", startedAt: timestamp }, timestamp); this.audit(organizerId, tournamentId, "TOURNAMENT_STARTED", timestamp); this.resolveByes(tournamentId); return this.state(tournamentId); });
  }
  recordResult(tournamentId: string, organizerId: string, expectedRevision: number, matchId: string, winnerId: string): BracketState {
    return this.persistence.transaction(() => { this.assertOwned(tournamentId, organizerId, expectedRevision, "ACTIVE"); const match = this.match(tournamentId, matchId); if (match.status !== "READY" || (winnerId !== match.player1Id && winnerId !== match.player2Id)) throw new BracketError("Winner is not eligible for this match.", "INVALID"); this.finish(match, winnerId, organizerId); this.resolveByes(tournamentId); return this.finishRevision(tournamentId, organizerId, expectedRevision); });
  }
  correct(tournamentId: string, organizerId: string, expectedRevision: number, matchId: string, winnerId: string, rollback = false): BracketState {
    return this.persistence.transaction(() => { this.assertOwned(tournamentId, organizerId, expectedRevision, "ACTIVE"); const match = this.match(tournamentId, matchId); if (!match.winnerId || (winnerId !== match.player1Id && winnerId !== match.player2Id)) throw new BracketError("Match cannot be corrected.", "INVALID"); const descendants = this.descendants(match); if (!rollback && descendants.some((item) => item.status === "COMPLETED")) throw new BracketError("Completed downstream matches require rollback.", "UNSAFE"); if (rollback) descendants.forEach((item) => this.persistence.bracket.clearMatch(item.id)); this.persistence.bracket.setMatch(match.id, { winnerId: null, loserId: null, status: "READY", completedAt: null }); this.finish(this.match(tournamentId, match.id), winnerId, organizerId, "MATCH_RESULT_CORRECTED"); this.rebuildInputs(tournamentId, descendants); this.resolveByes(tournamentId); return this.finishRevision(tournamentId, organizerId, expectedRevision, "MATCH_RESULT_CORRECTED"); });
  }
  private setupMutation(tid: string, oid: string, rev: number, event: "CONTESTANTS_MODIFIED" | "SEEDS_REORDERED" | "SEEDS_RANDOMIZED", work: () => void): BracketState { return this.persistence.transaction(() => { this.assertOwned(tid, oid, rev, "SETUP"); work(); this.persistence.tournaments.update(tid, rev, { venueName: this.persistence.tournaments.findById(tid)!.venueName }); this.audit(oid, tid, event); return this.state(tid); }); }
  private assertOwned(id: string, organizerId: string, revision: number, status: "SETUP" | "ACTIVE") { const state = this.state(id); if (state.tournament.organizerId !== organizerId || state.tournament.status !== status) throw new BracketError("Tournament is not available for this operation.", "INVALID"); if (state.tournament.revision !== revision) throw new BracketError("Tournament is stale.", "STALE"); return state; }
  private assertSeedOrder(tid: string, ids: string[]) { const actual = this.persistence.bracket.listContestants(tid).map((c) => c.id); if (ids.length !== actual.length || new Set(ids).size !== ids.length || ids.some((id) => !actual.includes(id))) throw new BracketError("Seed order must contain every contestant once.", "INVALID"); this.persistence.bracket.reseed(tid, ids); }
  private match(tid: string, id: string) { const match = this.persistence.bracket.findMatch(id); if (!match || match.tournamentId !== tid) throw new BracketError("Match not found.", "INVALID"); return match; }
  private finish(match: Match, winnerId: string, organizerId: string, type = "MATCH_RESULT_RECORDED") { const loserId = winnerId === match.player1Id ? match.player2Id : match.player1Id; const timestamp = clock(); this.persistence.bracket.setMatch(match.id, { winnerId, loserId, status: "COMPLETED", completedAt: timestamp }, timestamp); this.persistence.bracket.appendMatchEvent({ id: randomUUID(), tournamentId: match.tournamentId, matchId: match.id, eventType: type, payloadJson: JSON.stringify({ winnerId, loserId }), createdAt: timestamp }); if (match.nextWinnerMatchId) this.persistence.bracket.setMatch(match.nextWinnerMatchId, match.nextWinnerSlot === 1 ? { player1Id: winnerId } : { player2Id: winnerId }, timestamp); this.audit(organizerId, match.tournamentId, type === "MATCH_RESULT_RECORDED" ? "MATCH_RESULT_RECORDED" : "MATCH_RESULT_CORRECTED", timestamp); }
  private resolveByes(tid: string) { let changed = true; while (changed) { changed = false; for (const match of this.persistence.bracket.listMatches(tid)) { if (match.status !== "PENDING" || !this.persistence.bracket.incoming(match.id).every((item) => item.status === "COMPLETED" || item.status === "BYE")) continue; const winner = match.player1Id ?? match.player2Id; if (match.player1Id && match.player2Id) { this.persistence.bracket.setMatch(match.id, { status: "READY" }); changed = true; continue; } const timestamp = clock(); this.persistence.bracket.setMatch(match.id, { winnerId: winner, loserId: null, status: "BYE", completedAt: timestamp }, timestamp); this.persistence.bracket.appendMatchEvent({ id: randomUUID(), tournamentId: tid, matchId: match.id, eventType: "BYE_ADVANCED", payloadJson: JSON.stringify({ winnerId: winner }), createdAt: timestamp }); if (match.nextWinnerMatchId && winner) this.persistence.bracket.setMatch(match.nextWinnerMatchId, match.nextWinnerSlot === 1 ? { player1Id: winner } : { player2Id: winner }, timestamp); changed = true; } } }
  private finishRevision(tid: string, oid: string, revision: number, event: AuditEventType = "MATCH_RESULT_RECORDED"): BracketState { const matches = this.persistence.bracket.listMatches(tid); const final = matches.find((match) => !match.nextWinnerMatchId); const timestamp = clock(); if (final?.winnerId && (final.status === "COMPLETED" || final.status === "BYE")) { this.persistence.completeTournament(tid, revision, timestamp); this.audit(oid, tid, "TOURNAMENT_COMPLETED", timestamp); } else this.persistence.tournaments.update(tid, revision, { venueName: this.persistence.tournaments.findById(tid)!.venueName }, timestamp); this.persistence.bracket.setContestantStatuses(tid, matches.flatMap((match) => match.loserId ? [match.loserId] : []), timestamp); this.audit(oid, tid, event, timestamp); return this.state(tid); }
  private descendants(match: Match): Match[] { const result: Match[] = []; let next = match.nextWinnerMatchId; while (next) { const item = this.persistence.bracket.findMatch(next)!; result.push(item); next = item.nextWinnerMatchId; } return result; }
  private rebuildInputs(tid: string, descendants: Match[]) { const targetIds = new Set(descendants.map((m) => m.id)); for (const match of this.persistence.bracket.listMatches(tid)) if (match.nextWinnerMatchId && targetIds.has(match.nextWinnerMatchId) && (match.status === "COMPLETED" || match.status === "BYE") && match.winnerId) this.persistence.bracket.setMatch(match.nextWinnerMatchId, match.nextWinnerSlot === 1 ? { player1Id: match.winnerId } : { player2Id: match.winnerId }); }
  private audit(organizerId: string, tournamentId: string, eventType: Parameters<typeof this.persistence.bracket.appendAuditEvent>[0]["eventType"], timestamp = clock()) { this.persistence.bracket.appendAuditEvent({ id: randomUUID(), organizerId, tournamentId, eventType, payloadJson: "{}", createdAt: timestamp }); }
}
function validName(name: string): string { const value = name.trim(); if (!value || value.length > 200) throw new BracketError("Invalid contestant name.", "INVALID"); return value; }
